[package]
name = "ducd"
version = "0.1.0"
authors = ["Radoslav Georgiev <rgeorgiev583@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hotwatch = "0.4.3"
log = "0.4.14"
walkdir = "2.3.1"
