[package]
name = 'ducd'
version = '0.1.0'
authors = ['Radoslav Georgiev <rgeorgiev583@gmail.com>']
edition = '2018'

[dependencies]
hotwatch = '0.4.3'
log = '0.4.14'
walkdir = '2.3.1'
[target."cfg(not(windows))".dependencies]
signal-hook = '0.3.8'
